Repository Dallinger/Dallinger, pull requests merged in 2018-10, with the labels that each got.

#1416 Fix Travis build by installing Heroku via Snap
  .travis.yml
Labels: bug

#1419 Clock check: HIT does not exist
  dallinger/heroku/clock.py
  tests/test_heroku.py
Labels: bug

#1435 Improve reliability of bots
  dallinger/bots.py
  dallinger/db.py
  dallinger/experiment_server/experiment_server.py
  dallinger/heroku/worker.py
Labels: enhancement

#1431 Issues/1425 emergency notification
  dallinger/command_line.py
  dallinger/experiment_server/experiment_server.py
  dallinger/heroku/clock.py
  dallinger/heroku/messages.py
  dallinger/heroku/tools.py
  dallinger/notifications.py
  dallinger/recruiters.py
  dallinger/utils.py
  tests/conftest.py
  tests/test_command_line.py
  tests/test_deployment.py
  tests/test_experiment_server.py
  tests/test_heroku.py
  tests/test_notifications.py
  tests/test_recruiters.py
  tests/test_utils.py
Labels: bug

#1453 Update docker documentation for v5.0.0 release
  docs/source/creating_an_experiment.rst
  docs/source/developing_dallinger_setup_guide.rst
  docs/source/docker_setup.rst
  docs/source/installing_dallinger_for_users.rst
Labels: docs, enhancement, release

#1479 Unlink Required Experiment files section for v5 release
  docs/source/index.rst
Labels: docs, release

#1478 Update process termination in tests to work with entry point commands
  tests/conftest.py
Labels: bug
