Repository Dallinger/Dallinger, pull requests merged in 2018-09, with the labels that each got.

#1340 Fix typo in MultiRecruiter documentation
  docs/source/running_bots.rst
Labels: bug, docs

#1341 Log recruiter class on initialization
  dallinger/recruiters.py
Labels: enhancement

#1364 Add rtd configuration
  .readthedocs.yml
Labels: docs

#1336 Story 345: Change postgres status check to be more context agnostic
  dallinger/db.py
  dallinger/deployment.py
  tests/test_deployment.py
Labels: enhancement, feature

#1366 Story 396: overrecruited MTurk workers should be prompted to submit HIT
  dallinger/experiment_server/experiment_server.py
  dallinger/experiment_server/utils.py
  tests/test_experiment_server.py
Labels: bug

#1372 Better organise documentation for different users
  docs/source/dallinger_with_anaconda.rst
  docs/source/demo_index.rst
  docs/source/demoing_dallinger.rst
  docs/source/demos_on_heroku.rst
  docs/source/developing_dallinger_setup_guide.rst
  docs/source/index.rst
  docs/source/installing_dallinger_for_users.rst
  docs/source/installing_python.rst
  docs/source/troubleshooting.rst
Labels: docs, enhancement

#1388 Don't show database passwords to end users
  dallinger/config.py
Labels: bug
