Repository Dallinger/Dallinger, pull requests merged in 2018-08, with the labels that each got.

#1165 Tell pyupbot to ignore pycodestyle version 2.4.0
  .pyup.yml
  dev-requirements.txt
Labels: bug

#1227 docs - updated how to install pip on osx
  docs/source/developing_dallinger_setup_guide.rst
  docs/source/installing_dallinger_for_users.rst
Labels: docs

#1156 Extract deployments from command_line
  dallinger/command_line.py
  dallinger/deployment.py
  dallinger/experiment.py
  tests/test_command_line.py
  tests/test_deployment.py
  tests/test_heroku.py
Labels: enhancement

#1236 Fix py27 and launch bugs
  dallinger/deployment.py
  tests/test_deployment.py
Labels: bug

#1231 App Listing Command
  dallinger/command_line.py
  dallinger/deployment.py
  dallinger/heroku/tools.py
  docs/source/command_line_utility.rst
  requirements.txt
  tests/conftest.py
  tests/test_command_line.py
  tests/test_deployment.py
  tests/test_heroku.py
Labels: feature

#1240 Fix typos in docs for consistency
  docs/source/developing_dallinger_setup_guide.rst
Labels: docs, enhancement

#1273 Install docs improvements
  docs/source/creating_databases.rst
  docs/source/developing_dallinger_setup_guide.rst
  docs/source/heroku_redis.rst
  docs/source/installing_dallinger_for_users.rst
  docs/source/installing_postgres.rst
  docs/source/installing_python.rst
  docs/source/setup_virtualenv.rst
Labels: docs, enhancement

#1300 Fail early on heroku misconfiguration
  dallinger/deployment.py
  dallinger/heroku/__init__.py
  dallinger/heroku/tools.py
  tests/test_deployment.py
  tests/test_heroku.py
Labels: enhancement

#1299 Story 389: Don't grant MTurk Qualifications to over-recruited participants
  dallinger/experiment_server/experiment_server.py
  dallinger/experiment_server/worker_events.py
  dallinger/models.py
  dallinger/recruiters.py
  tests/test_experiment_server.py
  tests/test_recruiters.py
Labels: bug

#1311 Documentation improvements
  docs/source/developing_dallinger_setup_guide.rst
  docs/source/index.rst
  docs/source/learning_to_use_dallinger.rst
  docs/source/required_experiment_files.rst
Labels: docs, enhancement

#1291 Expire hits before destroying application
  dallinger/command_line.py
  docs/source/command_line_utility.rst
  tests/test_command_line.py
Labels: enhancement

#1322 Don't raise when optional 'heroku_team' key is absent
  dallinger/heroku/tools.py
  tests/test_heroku.py
Labels: bug
