Repository Dallinger/Dallinger, pull requests merged in 2018-11, with the labels that each got.

#1466 WIP: 5.0.0 release
  CHANGELOG.md
  dallinger/config.py
  dallinger/version.py
  demos/dlgr/demos/bartlett1932/requirements.txt
  demos/dlgr/demos/chatroom/requirements.txt
  demos/dlgr/demos/concentration/requirements.txt
  demos/dlgr/demos/function_learning/requirements.txt
  demos/dlgr/demos/iterated_drawing/requirements.txt
  demos/dlgr/demos/mcmcp/requirements.txt
  demos/dlgr/demos/rogers/requirements.txt
  demos/dlgr/demos/sheep_market/requirements.txt
  demos/dlgr/demos/snake/requirements.txt
  demos/dlgr/demos/twentyfortyeight/requirements.txt
  demos/dlgr/demos/vox_populi/requirements.txt
  demos/setup.py
  docs/source/conf.py
  docs/source/configuration.rst
  docs/source/the_experiment_class.rst
  setup.cfg
  setup.py
Labels: release

#1472 Remove demos from docs for v5 release
  docs/source/demoing_dallinger.rst
  docs/source/developing_dallinger_setup_guide.rst
  docs/source/index.rst
  docs/source/rewarding_participants.rst
  docs/source/running_bots.rst
  docs/source/troubleshooting.rst
  docs/source/waiting_rooms.rst
Labels: docs, release

#1494 Issues/1493 travis failing
  .travis.yml
  dallinger/experiment.py
  dallinger/experiment_server/gunicorn.py
  dallinger/recruiters.py
  tests/conftest.py
  tests/test_db.py
  tests/test_deployment.py
Labels: bug

#1504 Optimize redis connection in worker
  dallinger/mturk.py
  dallinger_scripts/worker.py
  tests/test_mturk.py
Labels: bug

#1496 Add tests and refactor MTurkLargeRecruiter
  dallinger/recruiters.py
  tests/test_agents.py
  tests/test_recruiters.py
Labels: enhancement

#1531 New RTD theme for documentation
  dev-requirements.txt
  docs/source/_static/custom.css
  docs/source/_static/grid.png
  docs/source/_static/grid_mini.png
  docs/source/_static/grid_small.png
  docs/source/_static/heroku.jpg
  docs/source/_static/style.css
  docs/source/aws_etc_keys.rst
  docs/source/conf.py
  docs/source/creating_an_experiment.rst
  docs/source/creating_databases.rst
  docs/source/demoing_dallinger.rst
  docs/source/developing_dallinger_setup_guide.rst
  docs/source/heroku_redis.rst
  docs/source/index.rst
  docs/source/installing_dallinger_for_users.rst
  docs/source/installing_postgres.rst
  docs/source/installing_python.rst
  docs/source/postico_and_postgres.rst
  docs/source/rewarding_participants.rst
  docs/source/running_bots.rst
  docs/source/setup_virtualenv.rst
  setup.py
Labels: docs, enhancement

#1535 Address FAQ in configuration docs
  docs/source/configuration.rst
Labels: docs

#1536 Release version 5.0.1
  CHANGELOG.md
  dallinger/version.py
  demos/dlgr/demos/bartlett1932/requirements.txt
  demos/dlgr/demos/chatroom/requirements.txt
  demos/dlgr/demos/concentration/requirements.txt
  demos/dlgr/demos/function_learning/requirements.txt
  demos/dlgr/demos/iterated_drawing/requirements.txt
  demos/dlgr/demos/mcmcp/requirements.txt
  demos/dlgr/demos/rogers/requirements.txt
  demos/dlgr/demos/sheep_market/requirements.txt
  demos/dlgr/demos/snake/requirements.txt
  demos/dlgr/demos/twentyfortyeight/requirements.txt
  demos/dlgr/demos/vox_populi/requirements.txt
  setup.cfg
  setup.py
Labels: release
