Repository Dallinger/Dallinger, pull requests merged in 2018-05, with the labels that each got.

#988 Story 333 configurable redis sizing
  dallinger/command_line.py
  dallinger/config.py
  docs/source/configuration.rst
  tests/conftest.py
  tests/test_command_line.py
Labels: enhancement

#989 Use vendored rq_gevent_worker
  .codecov.yml
  .coveragerc
  dallinger/heroku/rq_gevent_worker.py
  dallinger/heroku/worker.py
  setup.py
Labels: bug

#990 Fix warnings about psycopg2 and unicode_literals
  dallinger/command_line.py
  requirements.txt
Labels: bug

#978 Story 328: Mixed recruiters
  .eslintrc
  dallinger/command_line.py
  dallinger/config.py
  dallinger/experiment_server/experiment_server.py
  dallinger/experiment_server/worker_events.py
  dallinger/frontend/static/scripts/dallinger2.js
  dallinger/frontend/templates/base/ad.html
  dallinger/models.py
  dallinger/recruiters.py
  demos/dlgr/demos/bartlett1932/static/scripts/experiment.js
  demos/dlgr/demos/chatroom/static/scripts/experiment.js
  demos/dlgr/demos/concentration/static/scripts/experiment.js
  demos/dlgr/demos/function_learning/templates/ad.html
  demos/dlgr/demos/iterated_drawing/templates/ad.html
  demos/dlgr/demos/rogers/tests/tests.py
  demos/dlgr/demos/snake/static/scripts/experiment.js
  docs/source/index.rst
  docs/source/running_bots.rst
  docs/source/writing_bots.rst
  tests/conftest.py
  tests/experiment/templates/ad.html
  tests/test_db.py
  tests/test_experiment_server.py
  tests/test_heroku.py
  tests/test_models.py
  tests/test_recruiters.py
Labels: feature, reviewing

#992 Git status cleanup
  .gitignore
Labels: enhancement

#993 Story 331: Add configuration for recruitee qualification and add 'dallinger revoke' command
  dallinger/command_line.py
  dallinger/config.py
  dallinger/default_configs/local_config_defaults.txt
  dallinger/recruiters.py
  docs/source/command_line_utility.rst
  docs/source/configuration.rst
  tests/conftest.py
  tests/test_command_line.py
  tests/test_recruiters.py
Labels: feature

#1014 Use the default parameter we define
  dallinger/command_line.py
Labels: bug

#985 Release version 4.0.0
  CHANGELOG.md
Labels: release

#1033 Fix default is_overrecruited() behavior
  dallinger/experiment.py
  tests/test_experiment.py
Labels: bug
