Repository Dallinger/Dallinger, pull requests merged in 2018-12, with the labels that each got.

#1551 Issue 1550: fail early on undefined participant values
  dallinger/experiment_server/experiment_server.py
  tests/test_experiment_server.py
Labels: bug

#1557 Issues/1554 store undefined vals
  dallinger/frontend/static/scripts/dallinger2.js
Labels: bug

#1565 Reintroduce seven working demos into the docs
  demos/dlgr/demos/bartlett1932/config.txt
  demos/dlgr/demos/bartlett1932/static/scripts/experiment.js
  demos/dlgr/demos/bartlett1932/templates/consent.html
  demos/dlgr/demos/bartlett1932/templates/instructions/instruct-ready.html
  demos/dlgr/demos/chatroom/README.md
  demos/dlgr/demos/chatroom/config.txt
  demos/dlgr/demos/chatroom/experiment.py
  demos/dlgr/demos/chatroom/static/scripts/experiment.js
  demos/dlgr/demos/chatroom/templates/consent.html
  demos/dlgr/demos/chatroom/templates/instructions/instruct-ready.html
  demos/dlgr/demos/concentration/config.txt
  demos/dlgr/demos/concentration/experiment.py
  demos/dlgr/demos/concentration/static/scripts/experiment.js
  demos/dlgr/demos/concentration/templates/consent.html
  demos/dlgr/demos/concentration/templates/instructions/instruct-ready.html
  demos/dlgr/demos/function_learning/README.md
  demos/dlgr/demos/function_learning/config.txt
  demos/dlgr/demos/function_learning/experiment.py
  demos/dlgr/demos/function_learning/models.py
  demos/dlgr/demos/iterated_drawing/config.txt
  demos/dlgr/demos/iterated_drawing/experiment.py
  demos/dlgr/demos/iterated_drawing/static/scripts/experiment.js
  demos/dlgr/demos/iterated_drawing/templates/ad.html
  demos/dlgr/demos/iterated_drawing/templates/consent.html
  demos/dlgr/demos/iterated_drawing/templates/experiment.html
  demos/dlgr/demos/iterated_drawing/templates/layout.html
  demos/dlgr/demos/mcmcp/config.txt
  demos/dlgr/demos/mcmcp/experiment.py
  demos/dlgr/demos/mcmcp/templates/instructions/instruct-ready.html
  demos/dlgr/demos/rogers/config.txt
  demos/dlgr/demos/rogers/templates/instructions/instruct-2.html
  demos/dlgr/demos/rogers/templates/instructions/instruct-ready.html
  demos/dlgr/demos/sheep_market/config.txt
  demos/dlgr/demos/sheep_market/experiment.py
  demos/dlgr/demos/sheep_market/templates/ad.html
  demos/dlgr/demos/sheep_market/templates/consent.html
  demos/dlgr/demos/sheep_market/templates/layout.html
  demos/dlgr/demos/snake/config.txt
  demos/dlgr/demos/snake/experiment.py
  demos/dlgr/demos/snake/static/scripts/experiment.js
  demos/dlgr/demos/snake/templates/consent.html
  demos/dlgr/demos/snake/templates/instructions/instruct-ready.html
  demos/dlgr/demos/twentyfortyeight/config.txt
  demos/dlgr/demos/twentyfortyeight/experiment.py
  demos/dlgr/demos/vox_populi/config.txt
  demos/dlgr/demos/vox_populi/experiment.py
  docs/source/demo_index.rst
  docs/source/index.rst
  docs/source/rewarding_participants.rst
Labels: docs, enhancement

#1570 Remove legacy dallinger.js
  dallinger/command_line.py
  dallinger/deployment.py
  dallinger/frontend/static/scripts/dallinger.js
Labels: enhancement

#1571 Standardize on dallinger.goToPage()
  demos/dlgr/demos/chatroom/static/scripts/experiment.js
  docs/source/creating_an_experiment.rst
Labels: bug

#1572 Release version 5.0.2
  CHANGELOG.md
  dallinger/version.py
  demos/dlgr/demos/bartlett1932/requirements.txt
  demos/dlgr/demos/chatroom/requirements.txt
  demos/dlgr/demos/concentration/requirements.txt
  demos/dlgr/demos/function_learning/requirements.txt
  demos/dlgr/demos/iterated_drawing/requirements.txt
  demos/dlgr/demos/mcmcp/requirements.txt
  demos/dlgr/demos/rogers/requirements.txt
  demos/dlgr/demos/sheep_market/requirements.txt
  demos/dlgr/demos/snake/requirements.txt
  demos/dlgr/demos/twentyfortyeight/requirements.txt
  demos/dlgr/demos/vox_populi/requirements.txt
  setup.cfg
  setup.py
Labels: release

#1578 Correct dallinger export syntax in doc
  docs/source/experiment_data.rst
Labels: bug, docs
