Repository Dallinger/Dallinger, pull requests merged in 2019-01, with the labels that each got.

#1590 Issues/1547 rogers bug
  dallinger/networks.py
  demos/dlgr/demos/rogers/experiment.py
  demos/dlgr/demos/rogers/templates/consent.html
  tests/test_networks.py
Labels: bug

#1576 Add fixes and test for python 3.7 support
  .travis.yml
  constraints-deps.txt
  demos/setup.py
  setup.py
Labels: enhancement

#1587 Stories/448 missing fingerprint
  dallinger/frontend/static/scripts/dallinger2.js
  dallinger/frontend/templates/base/layout.html
Labels: bug

#1591 Check valid experiment dir
  dallinger/command_line.py
  demos/dlgr/demos/bartlett1932/experiment.py
  tests/test_command_line.py
Labels: enhancement

#1605 Release 5.0.3 take 2
  CHANGELOG.md
  THANKS.md
  setup.py
Labels: release

#1624 Prevent chrome from showing default browser popup on debug runs
  dallinger/deployment.py
  tests/test_deployment.py
Labels: enhancement

#1628 Pin chandler ruby gem
  .travis.yml
Labels: bug

#1627 Include Networks documentation in the main table of contents
  docs/source/index.rst
  docs/source/networks.rst
Labels: docs, enhancement

#1619 Profiles on osx
  dallinger/config.py
  dallinger/deployment.py
  tests/test_deployment.py
Labels: enhancement

#1629 Tweak styling of network docs
  docs/source/networks.rst
Labels: docs, enhancement

#1631 Release 5.0.4
  CHANGELOG.md
  dallinger/version.py
  demos/dlgr/demos/bartlett1932/requirements.txt
  demos/dlgr/demos/chatroom/requirements.txt
  demos/dlgr/demos/concentration/requirements.txt
  demos/dlgr/demos/function_learning/requirements.txt
  demos/dlgr/demos/iterated_drawing/requirements.txt
  demos/dlgr/demos/mcmcp/requirements.txt
  demos/dlgr/demos/rogers/requirements.txt
  demos/dlgr/demos/sheep_market/requirements.txt
  demos/dlgr/demos/snake/requirements.txt
  demos/dlgr/demos/twentyfortyeight/requirements.txt
  demos/dlgr/demos/vox_populi/requirements.txt
  setup.cfg
  setup.py
  yarn.lock
Labels: release

#1632 Fix indentation in CHANGELOG
  CHANGELOG.md
Labels: enhancement, release
