Repository Dallinger/Dallinger, pull requests merged in 2019-02, with the labels that each got.

#1638 Update CodeClimate configuration
  .codeclimate.yml
Labels: enhancement

#1641 More codeclimate tweaks
  .codeclimate.yml
Labels: enhancement

#1649 Restructure user and developer installations + misc doc fixes
  docs/source/_static/custom.css
  docs/source/conf.py
  docs/source/dallinger_with_anaconda.rst
  docs/source/demoing_dallinger.rst
  docs/source/developing_dallinger_setup_guide.rst
  docs/source/gsoc.rst
  docs/source/installing_dallinger_for_users.rst
Labels: docs, enhancement

#1644 Fix iterated drawing demo.
  demos/dlgr/demos/iterated_drawing/models.py
  demos/dlgr/demos/iterated_drawing/templates/layout.html
Labels: bug

#1656 Release version 5.0.5
  CHANGELOG.md
  dallinger/version.py
  demos/dlgr/demos/bartlett1932/requirements.txt
  demos/dlgr/demos/chatroom/requirements.txt
  demos/dlgr/demos/concentration/requirements.txt
  demos/dlgr/demos/function_learning/requirements.txt
  demos/dlgr/demos/iterated_drawing/requirements.txt
  demos/dlgr/demos/mcmcp/requirements.txt
  demos/dlgr/demos/rogers/requirements.txt
  demos/dlgr/demos/sheep_market/requirements.txt
  demos/dlgr/demos/snake/requirements.txt
  demos/dlgr/demos/twentyfortyeight/requirements.txt
  demos/dlgr/demos/vox_populi/requirements.txt
  demos/requirements.txt
  demos/setup.py
  docs/source/demo_index.rst
  setup.cfg
  setup.py
Labels: release

#1652 Log current attempt count when calling launch route
  CHANGELOG.md
  dallinger/deployment.py
  tests/test_deployment.py
Labels: bug, enhancement

#1663 Remove anaconda instructions from documentation
  docs/source/dallinger_with_anaconda.rst
  docs/source/index.rst
Labels: docs

#1673 Change Heroku apps parameter from --org to --team
  dallinger/heroku/tools.py
  tests/test_command_line.py
  tests/test_heroku.py
Labels: bug

#1674 Remove insecure Ubuntu postgres instructions
  docs/source/developing_dallinger_setup_guide.rst
  docs/source/installing_dallinger_for_users.rst
Labels: docs, enhancement

#1676 Various documentation fixes
  docs/source/developing_dallinger_setup_guide.rst
  docs/source/installing_dallinger_for_users.rst
  docs/source/python_module.rst
Labels: bug, docs, enhancement

#1679 Show "--verbose" as a best practice when running Dallinger experiments
  docs/source/demoing_dallinger.rst
Labels: docs, enhancement

#1668 Updates to `verify_package`
  CHANGELOG.md
  dallinger/command_line.py
Labels: bug

#1682 Wait for redis URL on heroku before connecting
  dallinger/deployment.py
Labels: bug

#1688 Release version 5.0.6
  CHANGELOG.md
  dallinger/version.py
  demos/dlgr/demos/bartlett1932/requirements.txt
  demos/dlgr/demos/chatroom/requirements.txt
  demos/dlgr/demos/concentration/requirements.txt
  demos/dlgr/demos/function_learning/requirements.txt
  demos/dlgr/demos/iterated_drawing/requirements.txt
  demos/dlgr/demos/mcmcp/requirements.txt
  demos/dlgr/demos/rogers/requirements.txt
  demos/dlgr/demos/sheep_market/requirements.txt
  demos/dlgr/demos/snake/requirements.txt
  demos/dlgr/demos/twentyfortyeight/requirements.txt
  demos/dlgr/demos/vox_populi/requirements.txt
  demos/requirements.txt
  demos/setup.py
  setup.cfg
  setup.py
Labels: release
