Repository Dallinger/Dallinger, pull requests merged in 2019-03, with the labels that each got.

#1693 Minor documentation fix
  docs/source/developing_dallinger_setup_guide.rst
  docs/source/installing_dallinger_for_users.rst
Labels: docs

#1695 Add link to beginner's guide
  docs/source/index.rst
Labels: docs

#1692 If a HIT is already deleted, don't raise from disable_hit()
  dallinger/mturk.py
Labels: bug

#1702 Add fast tox environment
  .travis.yml
  tests/conftest.py
  tests/test_api.py
  tests/test_command_line.py
  tests/test_config.py
  tests/test_data.py
  tests/test_demos.py
  tests/test_deployment.py
  tests/test_experiment_server.py
  tests/test_heroku.py
  tests/test_models.py
  tests/test_mturk.py
  tests/test_networks.py
  tests/test_processes.py
  tests/test_replay.py
  tests/test_replay_state.py
  tests/test_sockets.py
  tox.ini
Labels: enhancement

#1700 Black refinements
  .pre-commit-config.yaml
  tox.ini
Labels: enhancement

#1712 Update Ruby to fix Travis builds
  .travis.yml
Labels: bug

#1715 Fix precommit docs and fix duplicate annotation
  docs/source/classes.rst
  docs/source/developing_dallinger_setup_guide.rst
Labels: docs

#1717 Issues/gu 223 undef participant
  dallinger/frontend/static/scripts/dallinger2.js
  dallinger/frontend/static/scripts/dallinger2.test.js
  dallinger/frontend/templates/base/ad.html
Labels: enhancement

#1725 Have beginner docs show up in lefthand menu of documentation
  docs/source/index.rst
Labels: docs, enhancement

#1713 Check experiment size before copying
  dallinger/command_line.py
  dallinger/config.py
  dallinger/deployment.py
  dallinger/utils.py
  tests/test_command_line.py
  tests/test_config.py
  tests/test_deployment.py
Labels: enhancement

#1728 Expand command line documentation
  CHANGELOG.md
  dallinger/command_line.py
  docs/source/command_line_utility.rst
  tests/test_command_line.py
Labels: docs, enhancement

#1723 Separate slow S3 data tests for faster local ones
  tests/test_data.py
Labels: enhancement

#1722 Recruitment docs
  docs/source/index.rst
  docs/source/recruitment.rst
Labels: docs

#1734 Prep 5.0.7 release
  CHANGELOG.md
  dallinger/version.py
  demos/dlgr/demos/bartlett1932/requirements.txt
  demos/dlgr/demos/chatroom/requirements.txt
  demos/dlgr/demos/concentration/requirements.txt
  demos/dlgr/demos/function_learning/requirements.txt
  demos/dlgr/demos/iterated_drawing/requirements.txt
  demos/dlgr/demos/mcmcp/requirements.txt
  demos/dlgr/demos/rogers/requirements.txt
  demos/dlgr/demos/sheep_market/requirements.txt
  demos/dlgr/demos/snake/requirements.txt
  demos/dlgr/demos/twentyfortyeight/requirements.txt
  demos/dlgr/demos/vox_populi/requirements.txt
  demos/requirements.txt
  demos/setup.py
  setup.cfg
  setup.py
Labels: release

#1735 Prep changelog for next round of development
  CHANGELOG.md
Labels: enhancement
