Repository Dallinger/Dallinger, pull requests merged in 2020-03, with the labels that each got.

#2055 Upgrade MarkupSafe
  constraints-deps.txt
Labels: bug

#2053 Allow configuration of Heroku python version
  CHANGELOG.md
  dallinger/config.py
  dallinger/default_configs/global_config_defaults.txt
  dallinger/deployment.py
  dallinger/heroku/runtime.txt
  docs/source/configuration.rst
  tests/conftest.py
  tests/test_deployment.py
Labels: feature, needs docs

#2065 Issues/2013 exclude gitignore files
  CHANGELOG.md
  dallinger/command_line.py
  dallinger/deployment.py
  dallinger/utils.py
  docs/source/command_line_utility.rst
  docs/source/configuration.rst
  docs/source/creating_an_experiment.rst
  tests/test_command_line.py
  tests/test_deployment.py
  tests/test_utils.py
Labels: enhancement

#2071 2020 03 doc updates
  .travis.yml
  CHANGELOG.md
  constraints-deps.txt
  dev-constraints.txt
  docs/source/building_documentation.rst
  docs/source/configuration.rst
  docs/source/contributing_to_dallinger.rst
  docs/source/index.rst
  docs/source/running_the_tests.rst
  package.json
  tox.ini
  yarn.lock
Labels: docs

#2080 Release6.0.0
  CHANGELOG.md
  dallinger/version.py
  demos/dlgr/demos/bartlett1932/requirements.txt
  demos/dlgr/demos/chatroom/requirements.txt
  demos/dlgr/demos/concentration/requirements.txt
  demos/dlgr/demos/function_learning/requirements.txt
  demos/dlgr/demos/iterated_drawing/requirements.txt
  demos/dlgr/demos/mcmcp/requirements.txt
  demos/dlgr/demos/rogers/requirements.txt
  demos/dlgr/demos/sheep_market/requirements.txt
  demos/dlgr/demos/snake/requirements.txt
  demos/dlgr/demos/twentyfortyeight/requirements.txt
  demos/dlgr/demos/vox_populi/requirements.txt
  demos/requirements.txt
  demos/setup.py
  setup.cfg
  setup.py
Labels: release

#2062 Fix base url function
  dallinger/config.py
  dallinger/utils.py
  tests/test_config.py
  tests/test_utils.py
Labels: bug

#2084 Test fixups
  tests/conftest.py
Labels: enhancement

#2086 Handle case where HIT has no keywords
  dallinger/mturk.py
  tests/test_mturk.py
Labels: bug
