Repository Dallinger/Dallinger, pull requests merged in 2023-07, with the labels that each got.

#5346 Release v9.8.2
  .bumpversion.cfg
  CHANGELOG.md
  dallinger/version.py
  demos/dlgr/demos/bartlett1932/constraints.txt
  demos/dlgr/demos/chatroom/constraints.txt
  demos/dlgr/demos/concentration/constraints.txt
  demos/dlgr/demos/function_learning/constraints.txt
  demos/dlgr/demos/iterated_drawing/constraints.txt
  demos/dlgr/demos/mcmcp/constraints.txt
  demos/dlgr/demos/rogers/constraints.txt
  demos/dlgr/demos/sheep_market/constraints.txt
  demos/dlgr/demos/snake/constraints.txt
  demos/dlgr/demos/twentyfortyeight/constraints.txt
  demos/dlgr/demos/vox_populi/constraints.txt
  demos/requirements.txt
  demos/setup.py
  setup.py
Labels: release

#5321 Update documentation for making a release
  README.md
  docs/source/contributing_to_dallinger.rst
Labels: docs

#5367 Issues/5331 Experiment class owns submission logic
  dallinger/experiment.py
  dallinger/experiment_server/experiment_server.py
  dallinger/experiment_server/worker_events.py
  dallinger/recruiters.py
  tests/test_experiment.py
  tests/test_experiment_server.py
  tests/test_recruiters.py
Labels: enhancement

#5398 Remove --resolver=backtracking for pip-tools>=7.0.0
  dallinger/utils.py
  scripts/update_dependencies.sh
  scripts/update_experiments_constraints.sh
Labels: technical debt

#5419 5418 chromedriver fails to download in ci docker job
  Dockerfile
Labels: bug, testing

#5423 Update dependencies
  constraints.txt
  dev-requirements.txt
  requirements.txt
Labels: dependencies

#5434 Update setup-chromedriver to v2.1.0
  .github/workflows/ci.yml
Labels: bug, testing

#5435 Update dependencies
  constraints.txt
  dev-requirements.txt
  requirements.txt
Labels: dependencies

#5438 Release v9.9.0
  .bumpversion.cfg
  CHANGELOG.md
  dallinger/version.py
  demos/dlgr/demos/bartlett1932/constraints.txt
  demos/dlgr/demos/chatroom/constraints.txt
  demos/dlgr/demos/concentration/constraints.txt
  demos/dlgr/demos/function_learning/constraints.txt
  demos/dlgr/demos/iterated_drawing/constraints.txt
  demos/dlgr/demos/mcmcp/constraints.txt
  demos/dlgr/demos/rogers/constraints.txt
  demos/dlgr/demos/sheep_market/constraints.txt
  demos/dlgr/demos/snake/constraints.txt
  demos/dlgr/demos/twentyfortyeight/constraints.txt
  demos/dlgr/demos/vox_populi/constraints.txt
  demos/requirements.txt
  demos/setup.py
  setup.py
Labels: release
