Repository Dallinger/Dallinger, pull requests merged in 2024-12, with the labels that each got.

#7184 Update to rq v2
  constraints.txt
  dallinger/command_line/__init__.py
  dallinger_scripts/worker.py
  dev-requirements.txt
  pyproject.toml
  requirements.txt
Labels: dependencies, technical debt

#7252 Update dependencies
  constraints.txt
  dev-requirements.txt
  pyproject.toml
  requirements.txt
Labels: dependencies

#6788 Support choice of workspace and project in Dallinger configuration
  dallinger/command_line/__init__.py
  dallinger/command_line/docker.py
  dallinger/command_line/docker_ssh.py
  dallinger/command_line/prolific.py
  dallinger/command_line/utils.py
  dallinger/config.py
  dallinger/prolific.py
  dallinger/recruiters.py
  tests/test_prolific.py
  tests/test_recruiters.py
Labels: recruitment
