Repository Dallinger/Dallinger, pull requests merged in 2024-09, with the labels that each got.

#6767 Add sphinx-js back and point the repo to a tag of our fork with fixed pins
  constraints.txt
  dev-requirements.txt
  docs/source/conf.py
  pyproject.toml
Labels: dependencies

#6408 Add customizable worker loglevel
  dallinger/config.py
  dallinger/default_configs/local_config_defaults.txt
  dallinger/heroku/rq_gevent_worker.py
  dallinger/pytest_dallinger.py
  dallinger_scripts/worker.py
  docs/source/configuration.rst
Labels: feature

#6755 Prolific development recruiter: 5pts
  dallinger/experiment_server/experiment_server.py
  dallinger/prolific.py
  dallinger/recruiters.py
  tests/test_recruiters.py
Labels: recruitment

#6904 Fix building Sphinx documentation
  .readthedocs.yaml
  requirements-readthedocs.txt
  tox.ini
Labels: docs

#6938 Fix bug in loading loglevel_worker
  dallinger_scripts/worker.py
Labels: bug
