Repository Dallinger/Dallinger, pull requests merged in 2025-01, with the labels that each got.

#6220 Issues/5725 prolific duration exceeded
  .gitignore
  dallinger/config.py
  dallinger/db.py
  dallinger/experiment.py
  dallinger/experiment_server/worker_events.py
  dallinger/frontend/static/css/dashboard.css
  dallinger/heroku/clock.py
  dallinger/prolific.py
  dallinger/recruiters.py
  dallinger/utils.py
  docs/diagrams/participant_status_sync.md
  tests/test_dashboard.py
  tests/test_experiment.py
  tests/test_heroku.py
  tests/test_recruiters.py
Labels: recruitment

#7274 Release 11.0.0
  .bumpversion.cfg
  CHANGELOG.md
  constraints.txt
  dallinger/version.py
  demos/dlgr/demos/bartlett1932/constraints.txt
  demos/dlgr/demos/chatroom/constraints.txt
  demos/dlgr/demos/chatroom_ws/constraints.txt
  demos/dlgr/demos/concentration/constraints.txt
  demos/dlgr/demos/function_learning/constraints.txt
  demos/dlgr/demos/iterated_drawing/constraints.txt
  demos/dlgr/demos/mcmcp/constraints.txt
  demos/dlgr/demos/rogers/constraints.txt
  demos/dlgr/demos/sheep_market/constraints.txt
  demos/dlgr/demos/snake/constraints.txt
  demos/dlgr/demos/twentyfortyeight/constraints.txt
  demos/dlgr/demos/vox_populi/constraints.txt
  demos/requirements.txt
  demos/setup.py
  dev-requirements.txt
  pyproject.toml
  requirements.txt
  scripts/update_experiments_constraints.sh
Labels: release

#7301 Release 11.0.1
  .bumpversion.cfg
  CHANGELOG.md
  dallinger/version.py
  demos/dlgr/demos/bartlett1932/constraints.txt
  demos/dlgr/demos/chatroom/constraints.txt
  demos/dlgr/demos/chatroom_ws/constraints.txt
  demos/dlgr/demos/concentration/constraints.txt
  demos/dlgr/demos/function_learning/constraints.txt
  demos/dlgr/demos/iterated_drawing/constraints.txt
  demos/dlgr/demos/mcmcp/constraints.txt
  demos/dlgr/demos/rogers/constraints.txt
  demos/dlgr/demos/sheep_market/constraints.txt
  demos/dlgr/demos/snake/constraints.txt
  demos/dlgr/demos/twentyfortyeight/constraints.txt
  demos/dlgr/demos/vox_populi/constraints.txt
  demos/requirements.txt
  demos/setup.py
  pyproject.toml
Labels: release

#7332 Update dependencies
  constraints.txt
  dev-requirements.txt
  requirements.txt
Labels: dependencies
